name: PNPM CI Testing

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: "Create .env file"
        run: |
          touch .env.development
          echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env.development
      - run: pnpm install
      # - run: pnpm ci
      # - run: pnpm run build --if-present
      - run: pnpm test-details
